env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:react-perf/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - import
  - react
  - '@typescript-eslint'
  - prettier
  - react-perf
settings:
  import/parsers:
    '@typescript-eslint/parser': ['.ts', '.tsx']
  import/resolver:
    typescript: {}
rules: {
  arrow-body-style: 'off',
  import/extensions: ['error', 'ignorePackages', {
    ts: 'never',
    tsx: 'never'
  }],
  jsx-a11y/label-has-associated-control: ['error', { assert: 'either' }],
  prettier/prettier: 'warn',
  react/destructuring-assignment: ['error', 'never'],
  react/function-component-definition: ['error', { namedComponents: 'arrow-function' }],
  react/jsx-filename-extension: ['error', { extensions: ['.ts', '.tsx'] }],
  react/prop-types: 'off',
  react/react-in-jsx-scope: 'off',
  react/require-default-props: 'off'
}
